/**
 * DESAYUNOS MAÑANITAS — Catálogo de productos
 * Generado automáticamente desde productos_2026.xlsx
 * Para editar: abre el Excel, modifica y corre: node import-excel.js
 */

const PRODUCTS = [
  {
    id: 'mini-brunch',
    active: true,
    name: 'Mini Brunch',
    price: 75000,
    emoji: '🍳',
    category: 'economico',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural',
      'Parfait con yogurt natural fruta y granola y cuchara',
      'Cupcake',
    ],
    decoration: 'Caja decorativa con tapa de acetato , tarjeta y tag',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0)',
  },

  {
    id: 'brunch-el-rey-del-cafe',
    active: true,
    name: 'Brunch El rey del café',
    price: 80000,
    emoji: '☕',
    category: 'economico',
    badge: 'especial para Papá',
    note: 'La decoración es alusiva spara papá.',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural',
      'Manzana verde',
      'Cupcake',
      'Waffles con fruta y sirope',
    ],
    decoration: 'Caja con division  tapa de acetato decorativa, tarjeta , tag y vaso Mug.',
    gradient: 'linear-gradient(135deg, #6f4e37, #a0522d, #cd853f)',
  },

  {
    id: 'brunch-express',
    active: true,
    name: 'Brunch Express',
    price: 90000,
    emoji: '🥐',
    category: 'economico',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural',
      'Manzana verde',
      'Cupcake',
      'Waffles con fruta y sirope',
    ],
    decoration: 'Caja con division  tapa de acetato decorativa, tarjeta , tag y  vaso Mug.',
    gradient: 'linear-gradient(135deg, #fde2e4, #fad2e1, #fce4ec)',
  },

  {
    id: 'brunch-capitulo-de-pelicula',
    active: true,
    name: 'Brunch Capitulo de Pelicula',
    price: 95000,
    emoji: '🎬',
    category: 'economico',
    badge: null,
    note: 'La decoración es alusiva al Amor',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural',
      'Mini pancakes  con fresas y sirope',
      'Cupcake',
      'Parfait con yogurt natural fruta y granola',
    ],
    decoration: 'Bolsa Box, tarjeta , tag , lazo decorativo y vaso Mug.',
    gradient: 'linear-gradient(135deg, #f3e5f5, #e1bee7, #ce93d8)',
  },

  {
    id: 'petit-brunch',
    active: true,
    name: 'Petit Brunch',
    price: 100000,
    emoji: '🧇',
    category: 'economico',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural o café en leche',
      '3 waffles con fruta y sirope',
      'Cupcake',
      'Parfait con yogurt natural fruta y granola',
    ],
    decoration: 'Caja de madera decorativa, servilleta y cubiertos, 1 globo en helio, tarjeta y tag.',
    gradient: 'linear-gradient(135deg, #f8e8ee, #e8d5e0, #fce4ec)',
  },

  {
    id: 'brunch-capitulo-de-amor',
    active: true,
    name: 'Brunch Capitulo de Amor',
    price: 100000,
    emoji: '💖',
    category: 'economico',
    badge: '🌸 Especial Mamá',
    note: 'Desayuno exclusivo para un día especial o cumpleaños de Mamá',
    photos: [],
    includes: [
      'Sándwich con jamón, queso sabana de Alpina, vegetales y dip de la casa',
      'Bebida natural o café en leche',
      'Mini charcutero',
      'Cupcake',
      'Parfait con yogurt natural fruta y granola',
      'Bowl con waffles, fruta y sirope',
    ],
    decoration: 'Caja decorativa tipo libro, 2 globos en helio.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f48fb1, #e91e8c)',
  },

  {
    id: 'brunch-brisa-de-ternura',
    active: true,
    name: 'Brunch Brisa de Ternura',
    price: 110000,
    emoji: '🌸',
    category: 'economico',
    badge: '👩 Solo para Dama',
    note: 'Opción únicamente para dama',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso sabana de Alpina, vegetales y dip de la casa',
      'Bebida natural o café en leche',
      'Parfait con yogurt griego, granola, frutas y cuadrito de chocolate',
      'Cupcake',
    ],
    decoration: 'Tacita y platico de cerámica, caja decorativa con moño decorativo tarjeta y tag.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #ffcdd2)',
  },

  {
    id: 'royal-brunch',
    active: true,
    name: 'Royal Brunch',
    price: 150000,
    emoji: '👑',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Bowl con mix de frutas',
      'Cupcake',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Copa de cristal con parfait Yogurt griego granola y fruta',
    ],
    decoration: 'Bandeja de madera con mantelito de satín, ramillete de astromelias, cubiertos, tarjeta y tag, 2 globos en helio.',
    gradient: 'linear-gradient(135deg, #fce4ec, #e1bee7, #f3e5f5)',
  },

  {
    id: 'brunch-coquette-clasico',
    active: true,
    name: 'Brunch Coquette',
    price: 140000,
    emoji: '🍳',
    category: 'medio',
    badge: null,
    note: 'Exclusivo para mujeres',
    photos: [],
    includes: [
      'Sándwich de wafles con huevitos jamon queso y vegetales',
      'Bebida natural',
      'Mini Parfait con yogurt natural fruta y granola y cuchara',
      'Mix platanitos Manitoba',
    ],
    decoration: 'Canastilla organizadora metalica dorada con mantelito ,moño decorativo, botella de agua de vidirio  estilo coquette,tarjeta y tag',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0)',
  },

  {
    id: 'brunch-le-petit-waffle',
    active: true,
    name: 'Brunch le Petit Waffle',
    price: 150000,
    emoji: '🧇',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Bowl con mix de frutas',
      'Torre de waffles con fruta sirope o chocolate hersheys',
    ],
    decoration: 'Bandeja de madera con mantel de satín, plato de cerámica, ramillete de astromelias , tarjeta ,tag, 2globos en helio y cubierto.',
    gradient: 'linear-gradient(135deg, #fff3e0, #ffe0b2, #ffcc80)',
  },

  {
    id: 'brunch-oliva',
    active: true,
    name: 'Brunch Oliva',
    price: 160000,
    emoji: '🫒',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural y caliente',
      'Bowl con mix de frutas',
      'Waffles con fruta y sirope',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
    ],
    decoration: 'Bandeja de madera con mantel de satín, plato de cerámica, tarjeta y tag, 3 globos en helio y cubiertos',
    gradient: 'linear-gradient(135deg, #e8f5e9, #c8e6c9, #a5d6a7)',
  },

  {
    id: 'brunch-mes-amies',
    active: true,
    name: 'Brunch Mes Amies',
    price: 195000,
    emoji: '🌺',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Bowl con mix de frutas',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
      'Cajita de alfajores',
      'Mini torta vintage',
    ],
    decoration: 'Bandeja de madera con mantel de satín, ramillete de astromelias , 3 globos en helio, portarretrato + impresión de foto, tarjeta y tag, cubiertos.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #e8829e)',
  },

  {
    id: 'brunch-chic',
    active: true,
    name: 'Brunch Chic',
    price: 210000,
    emoji: '💎',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Bowl  en ceramica con mix de frutas',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
      'Mini torta vintage personal',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Cajita con alfajores',
    ],
    decoration: 'Bandeja de madera con mantel de satín, ramillete de astromelias , tarjeta , tag, 3 globos en helio y cubiertos.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #e8b4c8)',
  },

  {
    id: 'brunch-amelie',
    active: true,
    name: 'Brunch Amélie',
    price: 220000,
    emoji: '🌹',
    category: 'medio',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Mix de frutas frescas',
      'Cupcake',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
      'Waffles con fruta , sirope o chocolate Hersheys',
    ],
    decoration: 'Bandeja de madera con mantel de satín,vaso termo para café, ramillete de astromelias , tarjeta y tag, 3 globos en helio, cubierto.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f48fb1, #ec407a)',
  },

  {
    id: 'brunch-cherie',
    active: true,
    name: 'Brunch Chérie',
    price: 245000,
    emoji: '🍷',
    category: 'premium',
    badge: '💕 Romántico',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Plato en microcerámica con wrap de huevitos, jamón, queso, maicitos y vegetales frescos',
      'Bebida natural y caliente',
      'Bowl en cerámica con mix de frutas frescas.',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Torta Vintage',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
    ],
    decoration: 'Bandeja redonda de madera con mantel de satín, botella de vino rosado, 4 globos en helio, tarjeta y tag, cubiertos.',
    gradient: 'linear-gradient(135deg, #fff0f3, #ffccd5, #ff8fa3)',
  },

  {
    id: 'brunch-clasicc',
    active: true,
    name: 'Brunch Clasicc',
    price: 250000,
    emoji: '🌹',
    category: 'premium',
    badge: '⭐ Popular',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Bebida natural y caliente',
      'Copa de cristal con parfait de yogurt griego, granola premium y fruta',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Torta Vintage',
      'Mix de frutas',
      'Bowl de Charcutería',
    ],
    decoration: 'Bandeja de madera con mantel de satín, ramillete de rosas (20–25) , tarjeta y tag, 3 globos en helio, cubiertos.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f48fb1, #ec407a)',
  },

  {
    id: 'brunch-amor-de-pelicula',
    active: true,
    name: 'Brunch Amor de Pelicula',
    price: 250000,
    priceAlt: 210000,
    priceAltLabel: '',
    emoji: '🎥',
    category: 'premium',
    badge: '🎬 Especial',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural y caliente',
      'Sangría de vino tinto',
      'Waffles con fruta , sirope o chocolate Hersheys',
      'Parfait de yogurt griego, granola artesanal y fruta',
      'Torta vintage',
    ],
    decoration: 'Bandeja de madera con mantelito, libro de citas,tarjeta y tag, taza de cerámica y platico, tapa de cristal, 3 globos en helio',
    gradient: 'linear-gradient(135deg, #e8eaf6, #c5cae9, #9fa8da)',
  },

  {
    id: 'brunch-premium',
    active: true,
    name: 'Brunch Premium',
    price: 270000,
    emoji: '🍾',
    category: 'premium',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Baguette artesanal con arándanos, jamón de pavo, queso Gouda, lechuga y dip de la casa',
      'Waffle con fruta y sirope',
      'Omelette con jamón, queso mozzarella, vegetales y especias',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
      'Cajita de alfajores',
    ],
    decoration: 'Bandeja tipo mesa de madera con mantel de satín,portarretrato, botella de vino tinto, 3 globos en helio, tarjeta y tag, cubiertos.',
    gradient: 'linear-gradient(135deg, #4a1942, #8b1a4a, #c2185b)',
  },

  {
    id: 'brunch-criollo-chic',
    active: true,
    name: 'Brunch Criollo Chic',
    price: 275000,
    emoji: '🇨🇴',
    category: 'premium',
    badge: '🇨🇴 Criollo',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Chicharrón, arepas y 2 chorizos',
      'Bebida caliente + te Hatsu',
      'Wrap de huevos y chorizo',
      'Copa de cristal con parfait de yogurt griego, granola y frutas',
      'Torta artesanal',
      'bowl de Charcutería',
    ],
    decoration: 'Ramillete de hortensias , Termo de café , bandeja de madera con mantel de satín , cubiertos , tarjeta y tag, 3 globos en helio.',
    gradient: 'linear-gradient(135deg, #efebe9, #d7ccc8, #bcaaa4)',
  },

  {
    id: 'brunch-dulce-amanecer',
    active: true,
    name: 'Brunch Dulce Amanecer',
    price: 280000,
    emoji: '🌅',
    category: 'premium',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Sándwich de Croissant con jamón, queso mozzarella,  lechuga  y dip de la casa.',
      'Bebida natural y caliente',
      'Mini charcutero',
      'Cupcake',
      'Bowl Parfait con yogurt griego',
      'Waffles con fruta y sirope',
    ],
    decoration: 'Plato de cerámica y taza de café, tetera, tarjeta y tag, bandeja de madera con mantel de satín , cubiertos, globo burbuja + globos en helio.',
    gradient: 'linear-gradient(135deg, #fff8e1, #ffe082, #ffd54f)',
  },

  {
    id: 'brunch-coquette',
    active: true,
    name: 'Brunch Coquette premium',
    price: 290000,
    emoji: '🌹',
    category: 'premium',
    badge: '🏆 Exclusivo',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de maicitos, jamón, queso mozzarella y huevitos revueltos',
      'Bebida natural   o caliente',
      'Mix de frutas en bowl de cerámica  (el Bowl que tengamos disponible)',
      'Copa de cristal con parfait de yogurt griego, granola y fruta, con mermelada artesanal',
      'Dos waffles con sirope y frutas frescas',
      'Galleta decorada',
    ],
    decoration: 'Set de taza y plato en diseño de corazón, bandeja de madera con mantel de satín, tarjeta y tag, ramillete de rosas, opcional: pulserita artesanal como recuerdo',
    gradient: 'linear-gradient(135deg, #880e4f, #ad1457, #c62828)',
  },

  {
    id: 'brunch-je-taime',
    active: true,
    name: 'Brunch Je t\'aime',
    price: 280000,
    emoji: '🥂',
    category: 'premium',
    badge: '💕 Romántico',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'omellet con jamon queso y vegetales 1 croissan',
      'Bebida natural   o caliente',
      'Bowl con waffles fruta y sirope',
      'Copa de cristal con parfait de yogurt griego, granola y fruta',
      'Tortera de cristal con galletas artesanales o alfajores',
      'Vaso de vidrio con tapa de bambu y pitillo con jugo natural',
    ],
    decoration: 'portarretrato, mesa de madera con mantelito, cubiertos, tarjeta y tag, globos en helio',
    gradient: 'linear-gradient(135deg, #fde2e4, #e2ece9, #fad2e1)',
  },

  {
    id: 'brunch-kk',
    active: true,
    name: 'Brunch Expreso de Amor',
    price: 350000,
    emoji: '👑',
    category: 'premium',
    badge: '👑 Top',
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de huevitos, jamón, queso mozzarella y salami.',
      'Capuccino',
      'Charcutería',
      'Waffles con fruta y sirope',
      'Copa de cristal con parfait de yogurt griego, granola y fruta',
      'Torta personal Vintage',
      'Bolsa café Oma',
    ],
    decoration: 'Rosas (20–25) y jarrón, prensa francesa, bandeja de madera con mantel de satín y cubierto, tarjeta personalizada, tag y pincho, globos en helio.',
    gradient: 'linear-gradient(135deg, #c9a96e, #e8d5a8, #c9a96e)',
  },

  {
    id: 'brunch-le-petit-tresor',
    active: true,
    name: 'Brunch le Petit Trésor',
    price: 290000,
    emoji: '💎',
    category: 'premium',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'Wrap de filete de pollo, jamón, queso mozzarella y vegetales.',
      'Bebida natural',
      'Copa de cristal con parfait de yogurt griego, granola premium y fruta',
      'Panqueque con fruta fresa melocoton y chocolate.',
      'Mix de fruta',
      'copcake o alfajore',
    ],
    decoration: 'Bandeja de madera con mantel de satín, plato de cristal, joyerito, tarjeta y tag, 2 globos en helio globo burbuja y cubiertos.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0)',
  },

  {
    id: 'brunch-aventure-matinale',
    active: true,
    name: 'Brunch Aventure Matinale',
    price: 150000,
    emoji: '🎠',
    category: 'especial',
    badge: null,
    note: 'La decoración es alusiva según la ocasión',
    photos: [],
    includes: [
      'torre de waffles con jamon , queso y sirope',
      'Bebida natural  o milo',
      'Mix de fruta',
      'Cupcake',
      'Gomitas',
      'Gelatina y alpinito',
    ],
    decoration: 'Bandeja de madera con mantel de satín escenario infantil ( tu escoges  el personaje favorito), 2 globos en helio globo burbuja y cubiertos.',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0)',
  },

  {
    id: 'esencia-que-florece',
    active: true,
    name: 'Esencia que Florece',
    price: 100000,
    emoji: '🌸',
    category: 'madre',
    badge: '🌸 Día de la Madre',
    note: 'Edición especial Un Jardín Para Ella · Día de la Madre 2026',
    photos: [],
    includes: [
      'Sándwich croissant con jamón de pavo, queso colby jack y dip de la casa con tocineta',
      'Bebida Natural',
      'Galleta de mantequilla con glaseado en estilo de flor',
      'Mix de frutas enteras: fresones y uvas verdes',
      'Llavero tipo crochet en estilo de rosa',
    ],
    decoration: 'Buzón de cristal decorado con pequeñas florecitas, moño, tarjeta y tag decorativo',
    gradient: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #e8f5e9)',
  },

  {
    id: 'legado-que-florece',
    active: true,
    name: 'Legado que Florece',
    price: 130000,
    emoji: '🌿',
    category: 'madre',
    badge: '🌸 Día de la Madre',
    note: 'Edición especial Un Jardín Para Ella · Día de la Madre 2026',
    photos: [],
    includes: [
      'Sándwich croissant con jamón de pavo, queso colby jack y dip de la casa con tocineta',
      'Bebida Natural',
      'Galleta de mantequilla con glaseado en estilo de flor',
      'Bowl de parfait de frutas, con granola y yogurt griego',
      'Mini Charcutero: Salami, pepperoni, quesito, aceitunas y uchuva',
      'Llavero tipo crochet en estilo de rosa',
    ],
    decoration: 'Caja tipo pirámide, tarjeta y tag decorativo, 2 globos en helio',
    gradient: 'linear-gradient(135deg, #f3e5f5, #e1bee7, #fce4ec)',
  },

  {
    id: 'tu-amor-permanece',
    active: true,
    name: 'Tu Amor Permanece',
    price: 180000,
    emoji: '🤍',
    category: 'madre',
    badge: '🌸 Día de la Madre',
    note: 'Edición especial Un Jardín Para Ella · Día de la Madre 2026',
    photos: [],
    includes: [
      'Sándwich con pan artesanal, dip de pollo desmechado, queso colby jack y vegetales',
      'Bebida natural',
      'Waffles con fruta, sirope o chocolate',
      'Galleta de mantequilla con glaseado en estilo de flor',
      'Bowl de parfait con yogurt griego, fruta, granola y cuchara',
      'Termo en acero inoxidable con stiker alusivo al Día de la Madre',
      'Ramillete de flores astromelias o hortensias (según disponibilidad)',
    ],
    decoration: 'Bandeja de madera con corazón mediana, tarjeta, tag, mantel y globo burbuja decorativo',
    gradient: 'linear-gradient(135deg, #fce4ec, #f48fb1, #dcedc8)',
  },

  {
    id: 'amor-eterno',
    active: true,
    name: 'Amor Eterno',
    price: 300000,
    emoji: '👑',
    category: 'madre',
    badge: '👑 Premium Mamá',
    note: 'Edición especial Un Jardín Para Ella · Día de la Madre 2026 · Edición Premium',
    photos: [],
    includes: [
      'Sándwich con pan artesanal, dip de pollo desmechado, queso colby jack y vegetales. Mini waffles con arándanos, salami, quesito y pepperoni en plato de microcerámica con tapa de cristal',
      'Bebida natural',
      'Galletas de mantequilla con glaseado en estilo de flor y hoja',
      'Copa de parfait con yogurt griego, fruta y granola',
      'Torta artesanal rellena de frutos rojos y mermelada St. Dalfour',
      'Tacita de café con plato y tetera mediana en cerámica blanca',
    ],
    decoration: 'Bandeja de madera con corazón grande, tarjeta, tag, mantel y 3 globos en helio con stiker alusivo al Día de la Madre',
    gradient: 'linear-gradient(135deg, #4a1942, #880e4f, #c2185b)',
  },

  {
    id: 'princesa-peach-dulce-galaxy',
    active: true,
    name: 'Princesa Peach: Dulce Galaxy',
    price: 80000,
    emoji: '👸',
    category: 'clasico',
    badge: 'Día del Niño',
    note: 'Edición especial Día del Niño 2026 — 25 de abril · Temática Mario Bros Galaxy',
    photos: [],
    includes: [
      'Perro infantil con salchicha Zenú, queso mozzarella, dip de la casa, papitas y salsa al gusto',
      'Mini dona',
      'Yogurt y hojuelas de maíz',
      'Fresones',
      'Cajita de ganchitos y moñas',
      'Tarjeta y tag',
    ],
    decoration: 'Hermosa caja decorativa en papelería creativa alusiva a Mario Bros Galaxy.',
    gradient: 'linear-gradient(135deg, #ffd1e8, #ff9fc8, #ffe066)',
  },

  {
    id: 'galaxy-girl-nivel-estrella',
    active: true,
    name: 'Galaxy Girl: Nivel Estrella',
    price: 140000,
    emoji: '⭐',
    category: 'especial',
    badge: 'Día del Niño',
    note: 'Edición especial Día del Niño 2026 — 25 de abril · Temática Mario Bros Galaxy',
    photos: [],
    includes: [
      'Perro infantil con salchicha Zenú, queso mozzarella, dip de la casa, papitas y salsa al gusto',
      'Fresones',
      'Galleta alusiva a la edición Mario Bros',
      'Yogurt y hojuelas de maíz',
      'Mini waffles con sirope de miel',
      'Detalle cajita estilo bolsito con moñas, ganchitos y cachitos',
      'Tarjeta y tag',
    ],
    decoration: 'Caja decorativa en madera con escenario en papelería creativa alusiva a Mario Bros Galaxy.',
    gradient: 'linear-gradient(135deg, #e8d5f5, #c084fc, #ffe066)',
  },

  {
    id: 'nivel-1-aventura-mario',
    active: true,
    name: 'Nivel 1: Aventura Mario',
    price: 80000,
    emoji: '🍄',
    category: 'clasico',
    badge: 'Día del Niño',
    note: 'Edición especial Día del Niño 2026 — 25 de abril · Temática Mario Bros Galaxy',
    photos: [],
    includes: [
      'Perro infantil con salchicha Zenú, queso mozzarella, dip de la casa, papitas y salsa al gusto',
      'Mini dona',
      'Yogurt y hojuelas de maíz',
      'Fresones',
      'Detalle Mario Bros (juguete)',
      'Tarjeta y tag',
    ],
    decoration: 'Hermosa caja decorativa en papelería creativa alusiva a Mario Bros Galaxy.',
    gradient: 'linear-gradient(135deg, #ffd166, #e63946, #457b9d)',
  },

  {
    id: 'power-up-bros-desayuno-pro',
    active: true,
    name: 'Power Up Bros: Desayuno Pro',
    price: 140000,
    emoji: '🎮',
    category: 'especial',
    badge: 'Día del Niño',
    note: 'Edición especial Día del Niño 2026 — 25 de abril · Temática Mario Bros Galaxy',
    photos: [],
    includes: [
      'Perro infantil con salchicha Zenú, queso mozzarella, dip de la casa, papitas y salsa al gusto',
      'Fresones',
      'Galleta alusiva a la edición Mario Bros',
      'Yogurt y hojuelas de maíz',
      'Mini waffles con sirope de miel',
      'Detalle: Mario Bros coleccionable o Luigi (el que esté disponible)',
      'Tarjeta y tag',
    ],
    decoration: 'Caja decorativa en madera con escenario en papelería creativa alusiva a Mario Bros Galaxy.',
    gradient: 'linear-gradient(135deg, #d4edda, #28a745, #e63946)',
  }
];

// Para uso en Node.js (generate.js)
if (typeof module !== 'undefined') module.exports = PRODUCTS;
